baseURL: "https://baileybutler.com.au"
languageCode: "en-au"
title: "Bailey Butler"
theme: "PaperMod"

params:
    ShowBreadCrumbs: true
    defaultTheme: light
    disableThemeToggle: true
#    ShowReadingTime: true
    profileMode:
        enabled: true
        title: "Bailey Butler"
#        subtitle: "melbourne, vic"
#        imageUrl: "selfie.png"
#        imageHeight: 150
#        imageWidth: 150
        buttons:
            - name: "Programming"
              url: "/programming"
            - name: "Film"
              url: "/film"

    socialIcons:
        - name: "instagram"
          url: "https://instagram.com/bae1y"
        - name: "github"
          url: "https://github.com/baely"
        - name: "linkedin"
          url: "https://linkedin.com/in/baileybutler1"
