name: CD

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: |
          cd site
          hugo --minify

      - name: Service Account Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - name: Upload
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "site/public"
          destination: baileybutlerstatic
