on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: "/public"
          destination: baileybutlerstatic
