name: "CI"

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "site/public"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      - name: "Build"
        run: |
          cd site
          hugo --minify
          git config --global user.name baely
          git config --global user.email bailey.butler.234@gmail.com
          pwd
          ls -al
          git add --force site/public/*
          git commit -m "Generated site"
          git push
