on:
  push:
    branches:
      - "**"
    branches-ignore:
      - main
    paths-ignore:
      - "site/public"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Build"
        run: docker-compose up gen
