on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "site/public"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Build"
        run: docker-compose up gen
      - name: "Commit"
        run: |
          git config --global user.name baely
          git config --global user.email bailey.butler.234@gmail.com
          git commit -m "Generated site"
          git push
